#!/bin/bash

echo -n 'checking .vim/ '
WORKPATH=`pwd`

if [ ! -d ~/.vim ]; then
    ln -s $WORKPATH/.vim ~/.vim
    echo 'LINKED'
else
    echo 'OK'
fi

echo -n 'checking .vimrc '
if [ ! -f ~/.vimrc ]; then
    ln -s $WORKPATH/.vimrc ~/.vimrc
    echo 'LINKED'
else
    echo 'OK'
fi

echo -n 'checking .screenrc '
if [ ! -f ~/.screenrc ]; then
    ln -s $WORKPATH/.screenrc ~/.screenrc
    echo 'LINKED'
else
    echo 'OK'
fi

echo -n 'checking .ctags '
if [ ! -f ~/.ctags ]; then
    ln -s $WORKPATH/.ctags ~/.ctags
    echo 'LINKED'
else
    echo 'OK'
fi

echo 'DONE'


